source 'https://rubygems.org'

gem 'rails', '3.2.15'
gem 'sqlite3'

gem 'sass-rails',   '~> 3.2.3'
gem 'coffee-rails', '~> 3.2.1'

group :assets do
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'foundation-rails', "~> 5.1.0"
gem 'foundation-icons-sass-rails'

group :development do
  gem 'better_errors'
  gem "binding_of_caller"
  gem 'quiet_assets'
  # gem 'rack-mini-profiler'
end

gem "cancan"
gem 'devise'
gem 'compass-rails'
gem "font-awesome-rails", '~> 4.0.0'
gem "jquery-ui-rails"
gem 'thin'
